name: 'Publish Release'

on:
  push:
    branches:
      - master
      - adding-build-workflows # For testing
  # workflow_dispatch:


jobs:
  build:
    name: 'Build Release and publish'
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      build_dir: /home/runner/work/code-macros/code-macros/builds
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 17
      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libudev-dev
      - name: install app dependencies and build it
        run: yarn && yarn build
      - name: Build Tauri app
        uses: JonasKruckenberg/tauri-build@v1.0.3
        id: tauri_build
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path:  "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
