name: 'Publish Release'

on:
  push:
    branches:
      - master
      - adding-build-workflows # For testing
  # workflow_dispatch:


jobs:
  publish-tauri:
    name: 'Build Release and publish'
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    env:
      build_dir: /home/runner/work/code-macros/code-macros/builds
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 17
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        #   releaseName: 'Code-Macros v__VERSION__'
        #   body: 'See the assets to download this version and install.'
        #   draft: false
        #   prerelease: false
        #   # includeDebug: true # whether to include a debug build or not
      - run: ls -l $build_dir