name: 'Publish Release'

on:
  push:
    branches:
      - master
      - adding-build-workflows # For testing
      - build-workflow-manual # For testing
  # workflow_dispatch:


jobs:
  build:
    name: 'Build Release and publish'
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      build_dir: /home/runner/work/code-macros/code-macros/builds
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # https://tauri.app/v1/guides/getting-started/prerequisites/
      - run: sudo apt update
      - name: Install dependencies
        run: |
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - run: yarn
      - run: yarn tauri build
      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ env.build_dir }}